#define icons_idc 46300

    class FZF_ICHud_Rsc
    {
        idd = -1;
        movingEnable = 1;
        enableSimulation = 1;
        enableDisplay = 1;

        onLoad = "_this call FZF_ICHud_Load";

        duration = 99999999999999999;
        fadein  = 0;
        fadeout = 0;
        class controls
        {
            class Icons : w_RscStructuredText
            {
			idc = -1;
			type = 13;
			style = ST_LEFT;
			x = 0.5;
			y = 0.5;
			w = 1;
			h = 1;
			size = 0.08;
			colorBackground[] = {0,0,0,0};
			colortext[] = {0,0,0,0.7};
			text ="";
		
            };
		class PlayerIcon00:Icons {idc = icons_idc +  0;};
		class PlayerIcon01:Icons {idc = icons_idc +  1;};
		class PlayerIcon02:Icons {idc = icons_idc +  2;};
		class PlayerIcon03:Icons {idc = icons_idc +  3;};
		class PlayerIcon04:Icons {idc = icons_idc +  4;};
		class PlayerIcon05:Icons {idc = icons_idc +  5;};
		class PlayerIcon06:Icons {idc = icons_idc +  6;};
		class PlayerIcon07:Icons {idc = icons_idc +  7;};
		class PlayerIcon08:Icons {idc = icons_idc +  8;};
		class PlayerIcon09:Icons {idc = icons_idc +  9;};
		class PlayerIcon10:Icons {idc = icons_idc + 10;};
		class PlayerIcon11:Icons {idc = icons_idc + 11;};
		class PlayerIcon12:Icons {idc = icons_idc + 12;};
		class PlayerIcon13:Icons {idc = icons_idc + 13;};
		class PlayerIcon14:Icons {idc = icons_idc + 14;};
		class PlayerIcon15:Icons {idc = icons_idc + 15;};
		class PlayerIcon16:Icons {idc = icons_idc + 16;};
		class PlayerIcon17:Icons {idc = icons_idc + 17;};
		class PlayerIcon18:Icons {idc = icons_idc + 18;};
		class PlayerIcon19:Icons {idc = icons_idc + 19;};
		class PlayerIcon20:Icons {idc = icons_idc + 20;};
		class PlayerIcon21:Icons {idc = icons_idc + 21;};
		class PlayerIcon22:Icons {idc = icons_idc + 22;};
		class PlayerIcon23:Icons {idc = icons_idc + 23;};
		class PlayerIcon24:Icons {idc = icons_idc + 24;};
		class PlayerIcon25:Icons {idc = icons_idc + 25;};
		class PlayerIcon26:Icons {idc = icons_idc + 26;};
		class PlayerIcon27:Icons {idc = icons_idc + 27;};
		class PlayerIcon28:Icons {idc = icons_idc + 28;};
		class PlayerIcon29:Icons {idc = icons_idc + 29;};
		class PlayerIcon30:Icons {idc = icons_idc + 30;};
		class PlayerIcon31:Icons {idc = icons_idc + 31;};
		class PlayerIcon32:Icons {idc = icons_idc + 32;};
		class PlayerIcon33:Icons {idc = icons_idc + 33;};
		class PlayerIcon34:Icons {idc = icons_idc + 34;};
		class PlayerIcon35:Icons {idc = icons_idc + 35;};
		class PlayerIcon36:Icons {idc = icons_idc + 36;};
		class PlayerIcon37:Icons {idc = icons_idc + 37;};
		class PlayerIcon38:Icons {idc = icons_idc + 38;};
		class PlayerIcon39:Icons {idc = icons_idc + 39;};
		class PlayerIcon40:Icons {idc = icons_idc + 40;};
		class PlayerIcon41:Icons {idc = icons_idc + 41;};
		class PlayerIcon42:Icons {idc = icons_idc + 42;};
		class PlayerIcon43:Icons {idc = icons_idc + 43;};
		class PlayerIcon44:Icons {idc = icons_idc + 44;};
		class PlayerIcon45:Icons {idc = icons_idc + 45;};
		class PlayerIcon46:Icons {idc = icons_idc + 46;};
		class PlayerIcon47:Icons {idc = icons_idc + 47;};
		class PlayerIcon48:Icons {idc = icons_idc + 48;};
		class PlayerIcon49:Icons {idc = icons_idc + 49;};
		class PlayerIcon50:Icons {idc = icons_idc + 50;};
		class PlayerIcon51:Icons {idc = icons_idc + 51;};
		class PlayerIcon52:Icons {idc = icons_idc + 52;};
		class PlayerIcon53:Icons {idc = icons_idc + 53;};
		class PlayerIcon54:Icons {idc = icons_idc + 54;};
		class PlayerIcon55:Icons {idc = icons_idc + 55;};
		class PlayerIcon56:Icons {idc = icons_idc + 56;};
		class PlayerIcon57:Icons {idc = icons_idc + 57;};
		class PlayerIcon58:Icons {idc = icons_idc + 58;};
		class PlayerIcon59:Icons {idc = icons_idc + 59;};
		class PlayerIcon60:Icons {idc = icons_idc + 60;};
		class PlayerIcon61:Icons {idc = icons_idc + 61;};
		class PlayerIcon62:Icons {idc = icons_idc + 62;};
		class PlayerIcon63:Icons {idc = icons_idc + 63;};
		class PlayerIcon64:Icons {idc = icons_idc + 64;};
		class PlayerIcon65:Icons {idc = icons_idc + 65;};
		class PlayerIcon66:Icons {idc = icons_idc + 66;};
		class PlayerIcon67:Icons {idc = icons_idc + 67;};
		class PlayerIcon68:Icons {idc = icons_idc + 68;};
		class PlayerIcon69:Icons {idc = icons_idc + 69;};
		class PlayerIcon70:Icons {idc = icons_idc + 70;};
		class PlayerIcon71:Icons {idc = icons_idc + 71;};
		class PlayerIcon72:Icons {idc = icons_idc + 72;};
		class PlayerIcon73:Icons {idc = icons_idc + 73;};
		class PlayerIcon74:Icons {idc = icons_idc + 74;};
		class PlayerIcon75:Icons {idc = icons_idc + 75;};
		class PlayerIcon76:Icons {idc = icons_idc + 76;};
		class PlayerIcon77:Icons {idc = icons_idc + 77;};
		class PlayerIcon78:Icons {idc = icons_idc + 78;};
		class PlayerIcon79:Icons {idc = icons_idc + 79;};
		class PlayerIcon80:Icons {idc = icons_idc + 80;};
		class PlayerIcon81:Icons {idc = icons_idc + 81;};
		class PlayerIcon82:Icons {idc = icons_idc + 82;};
		class PlayerIcon83:Icons {idc = icons_idc + 83;};
		class PlayerIcon84:Icons {idc = icons_idc + 84;};
		class PlayerIcon85:Icons {idc = icons_idc + 85;};
		class PlayerIcon86:Icons {idc = icons_idc + 86;};
		class PlayerIcon87:Icons {idc = icons_idc + 87;};
		class PlayerIcon88:Icons {idc = icons_idc + 88;};
		class PlayerIcon89:Icons {idc = icons_idc + 89;};
		class PlayerIcon90:Icons {idc = icons_idc + 90;};
		class PlayerIcon91:Icons {idc = icons_idc + 91;};
		class PlayerIcon92:Icons {idc = icons_idc + 92;};
		class PlayerIcon93:Icons {idc = icons_idc + 93;};
		class PlayerIcon94:Icons {idc = icons_idc + 94;};
		class PlayerIcon95:Icons {idc = icons_idc + 95;};
		class PlayerIcon96:Icons {idc = icons_idc + 96;};
		class PlayerIcon97:Icons {idc = icons_idc + 97;};
		class PlayerIcon98:Icons {idc = icons_idc + 98;};
		class PlayerIcon99:Icons {idc = icons_idc + 99;};
		};
	};
